services:
  caddy-gen:
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/ubuntu/zazubot/.typebot/caddy-certificates:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - typebot-builder
      - typebot-viewer
  typebot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    labels:
      virtual.host: "app.zazubot.com" # change to your domain
      virtual.port: "3000"
      virtual.tls-email: "info@zazubot.com" # change to your email
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # See https://docs.zazubot.com/self-hosting/configuration for more configuration options
    env_file:
      - .env
  typebot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    labels:
      virtual.host: "hi.zazubot.com" # change to your domain
      virtual.port: "3000"
      virtual.tls-email: "info@zazubot.com" # change to your email
      # Necessary to enable message streaming
      virtual.proxy.directives: |
        flush_interval -1
    restart: always
    # See https://docs.zazubot.com/self-hosting/configuration for more configuration options
    env_file:
      - .env
  mail:
    image: bytemark/smtp
    restart: always
  minio:
    labels:
      virtual.host: "storage.zazubot.com" # change to your domain
      virtual.port: "9000"
      virtual.tls-email: "info@zazubot.com" # change to your email
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3-data:/data
  # This service just make sure a bucket with the right policies is created
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "

volumes:
  db-data:
  s3-data:
